version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: db123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user123 -d db123"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "13000:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development

volumes:
  pgdata:
